CP_ratio: 0.25
EARLY_STOP_PATIENCE: 100
EARLY_STOP_THRESHOLD: 0.5
batch_size: 16
d_model: 128
dc_offset: 0
dim_feedforward: 64
dropout: 0.09
epochs: 4000
gain: 20
lr: 0.0007
modulator: m5_apsk_constellation
nhead: 8
nlayers: 4
num_symbols_per_frame: 1
pre_layer_norm: false
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
weight_init: default