EARLY_STOP_PATIENCE: 2000
EARLY_STOP_THRESHOLD: 0.5
batch_size: 32
d_model: 128
dc_offset: 0
dim_feedforward: 512
dropout: 0.22424673502256262
epochs: 10000
gain: 20
lr: 0.00020882045357212015
modulator: qpsk
nhead: 2
nlayers: 3
plot_frequency: 32
save_model_frequency: 500
