EARLY_STOP_PATIENCE: 15
EARLY_STOP_THRESHOLD: 0.5
batch_size: 16
d_model: 64
dc_offset: 0
dim_feedforward: 256
dropout: 0.08257039157025751
epochs: 4000
gain: 20
lr: 0.0004651833287878912
modulator: m5_apsk_constellation
nhead: 4
nlayers: 3
optuna_study: labview_transformer_20250529_203446
plot_frequency: 16
save_model_frequency: 500
