EARLY_STOP_PATIENCE: 200
EARLY_STOP_THRESHOLD: 0.5
batch_size: 1
d_model: 256
dc_offset: 0
dim_feedforward: 128
dropout: 0.005097467775547915
epochs: 2
gain: 20
lr: 0.0007527158327746758
modulator: m5_apsk_constellation
nhead: 8
nlayers: 5
num_symbols_per_frame: 4
optuna_study: labview_transformer_20250604_180027
plot_frequency: 1
save_model_frequency: 500
scheduler_type: warmup
warmup_steps: 11
weight_init: xavier
