EARLY_STOP_PATIENCE: 100
EARLY_STOP_THRESHOLD: 0.5
OFDM_period: 10000.0
batch_size: 16
cnn: false
d_model: 64
dc_offset: 0
dim_feedforward: 256
dropout: 0.08057083615921015
epochs: 10
f3dB: 6000000.0
gain: 20
lr: 0.00118593977395718
modulator: m5_apsk_constellation
nhead: 4
nlayers: 2
num_points_time: 16384
num_symbols_per_frame: 1
optuna_study: labview_transformer_20250609_113319
plot_frequency: 1
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
warmup_steps: 1
weight_init: default
