CP_ratio: 0.25
EARLY_STOP_PATIENCE: 1
EARLY_STOP_THRESHOLD: 0.5
batch_size: 1
channel_derivative_type: ici_matrix
d_model: 64
dc_offset: 0
dim_feedforward: 512
dropout: 0.050149695282096396
epochs: 250
gain: 20
ici_window_length: 370
lr: 0.0024071518244157476
matrix_regularization: 1.9895512695845604e-06
modulator: m5_apsk_constellation
nhead: 8
nlayers: 2
num_symbols_per_frame: 1
optuna_study: labview_transformer_20250620_105650
plot_frequency: 10
pre_layer_norm: false
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
weight_init: default
