CP_ratio: 0.25
EARLY_STOP_PATIENCE: 1000000000
EARLY_STOP_THRESHOLD: 0.5
batch_size: 16
d_model: 128
dc_offset: 0
dim_feedforward: 64
dropout: 0.09
epochs: 4000
gain: 20
lr: 0.0007
modulator: m5_apsk_constellation
nhead: 8
nlayers: 4
num_symbols_per_frame: 1
pre_layer_norm: false
save_model_frequency: 1000000000
scheduler_type: reduce_lr_on_plateu
weight_init: default
freq_embed_type: sinusoidal
normalize_freq: true
matrix_regularization: 0.0001
channel_derivative_type: ici_matrix
ici_window_length: 1000
plot_frequency: 10