EARLY_STOP_PATIENCE: 2
EARLY_STOP_THRESHOLD: 0.5
batch_size: 1
d_model: 64
dc_offset: 0
dim_feedforward: 512
dropout: 0.23186071680745243
epochs: 10000
gain: 20
lr: 0.0003905952431854349
modulator: qpsk
nhead: 8
nlayers: 3
plot_frequency: 1
save_model_frequency: 500
