CP_ratio: 0.25
EARLY_STOP_PATIENCE: 125
EARLY_STOP_THRESHOLD: 0.5
batch_size: 16
channel_derivative_type: ici_matrix
d_model: 64
dc_offset: 0
dim_feedforward: 64
dropout: 0.07151161584911593
epochs: 4000
gain: 20
ici_window_length: 10000
lr: 5.9893723110670745e-05
matrix_regularization: 2.7392035305665175e-05
modulator: m5_apsk_constellation
nhead: 4
nlayers: 3
num_symbols_per_frame: 1
optuna_study: labview_transformer_20250621_114445
plot_frequency: 32
pre_layer_norm: false
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
weight_init: default
