CP_ratio: 0.25
EARLY_STOP_PATIENCE: 187
EARLY_STOP_THRESHOLD: 0.5
batch_size: 16
channel_derivative_type: linear
d_model: 128
dc_offset: 0
dim_feedforward: 256
dropout: 0.2979122902090939
epochs: 4000
gain: 20
ici_window_length: 10000
lr: 0.0002650369494496869
matrix_regularization: 0.0001
modulator: m5_apsk_constellation
nhead: 8
nlayers: 4
num_symbols_per_frame: 1
optuna_study: labview_transformer_20250627_175759
plot_frequency: 32
pre_layer_norm: false
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
weight_init: default
