CP_ratio: 0.25
EARLY_STOP_PATIENCE: 500
EARLY_STOP_THRESHOLD: 0.5
batch_size: 16
channel_derivative_type: linear
d_model: 64
dc_offset: 0
dim_feedforward: 128
dropout: 0.1550742303286682
epochs: 4000
gain: 20
ici_window_length: 370
lr: 0.0007317246556926074
modulator: m5_apsk_constellation
nhead: 4
nlayers: 2
num_symbols_per_frame: 1
plot_frequency: 16
pre_layer_norm: false
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
weight_init: default