EARLY_STOP_PATIENCE: 100
EARLY_STOP_THRESHOLD: 0.5
OFDM_period: 10000.0
batch_size: 1
cnn: false
d_model: 128
dc_offset: 0
dim_feedforward: 128
dropout: 0.17291625712980935
epochs: 125
f3dB: 6000000.0
gain: 20
lr: 0.0003098968991599046
modulator: m5_apsk_constellation
nhead: 4
nlayers: 4
num_points_time: 16384
num_symbols_per_frame: 1
optuna_study: labview_transformer_20250608_183748
plot_frequency: 1
save_model_frequency: 500
scheduler_type: reduce_lr_on_plateu
warmup_steps: 4
weight_init: default
