EARLY_STOP_PATIENCE: 2000
EARLY_STOP_THRESHOLD: 0.5
batch_size: 1
d_model: 128
dc_offset: 0
dim_feedforward: 128
dropout: 0.17184475829590934
epochs: 2
gain: 20
lr: 0.0014880382950010244
modulator: qpsk
nhead: 4
nlayers: 6
optuna_study: labview_transformer_20250529_121503
plot_frequency: 1
save_model_frequency: 500
