name: mldrivenpeled
channels:
  - conda-forge
  - pytorch # Necessary for pytorch installation. If using cuda, may need different import
  - defaults
dependencies:
  - pip>=23
  - python=3.11
  - numpy>=1.26
  - matplotlib>=3.8
  - pandas>=2.0
  - pytorch>=2.2.1
  - scikit-learn
  - tqdm