CP_ratio: 0.25
batch_size: 16
d_model: 384
dc_offset: 0
dim_feedforward: 768
dropout: 0.2112313688914284
epochs: 1
gain: 20
lr: 0.0004275073658015301
nhead: 96
nlayers: 4
num_symbols_per_frame: 1
pre_layer_norm: false
scheduler_type: reduce_lr_on_plateu
weight_init: default
freq_embed_type: sinusoidal
normalize_freq: true
Nf: 370
Nt: 1