batch_size: 16
Nt: 1
Nf: 370
flow: 300000
fhigh: 4e6
subcarrier_spacing: 1e4
epochs: 1000
d_model: 128
dim_feedforward: 256
nhead: 4
nlayers: 5
dropout: 0.04
lr: 0.0002650369494496869
modulator: m5_apsk_constellation
save_model_frequency: 500